Ballchasy - bcManager update
RSC-NA/bot-RSCBot pull request #1
Opened 2022-07-14 00:14 UTC by BenjaminHunt

# bcManager
- re-writes all `bcManager` code
- uses python-ballchasing api wrapper (https://github.com/Rolv-Arild/python-ballchasing)
- uses roles for ballchasing tier name hierarchy (1Premier, 2Master, etc.)
- includes customizable timezones (used for ballchasing searches, Default: `"America/New_York"`, Reference: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
- posts and updates a status embed for `reportMatches` command while processing match replays
- includes game and match validations
- posts score report to score reporting channel
- updates match cog info after score is reported
- `<p>bcr` processes a player's match results (temporary)
- `<p>reportMatches` processes all match replays for current match day

# match
- updates add match commands to require `match_type` (Regular season, wildcard, etc) and `match_format` (4-gs, bo-5, etc)
- removes lobby info inputs in add match behavior
- adds lobby info validation to avoid collisions on match days

2022-07-14 15:26 UTC, blister requested changes
Overall, code looks great. One minor nitpick in naming convention and one bug that will pop up on November 6th when the time changes.

2022-07-14 15:26 UTC, blister commented on bcManager/__init__.py
> +from .bcConfig import bcConfig
Tiny nitpick, but the naming convention of the module has capital `BC` directly below this, and you went with lower case `bc`. Feels incorrect. Obviously it doesn't matter in code, but I love consistency.

2022-07-14 15:26 UTC, blister commented on bcManager/bcConfig.py
> +    ZONE_ADJ = "-04:00"
This zone adjustment doesn't take into account daylight savings time. Part of the year has Eastern at EST `-5`.

2022-07-14 17:55 UTC, blister approved these changes
Nicely done. Timezones are always a pain in the ass. :(

2022-07-14 17:55 UTC, blister approved these changes

2022-07-14 18:28 UTC, blister approved these changes
I concur!

2022-07-14 18:35 UTC, blister approved these changes
Trying again.

2022-07-15 16:00 UTC, merged

2022-07-15 16:26 UTC, BenjaminHunt commented
`BCConfig.py` name wasn't updated, so that was added as a direct commit to master: https://github.com/RSC-NA/bot-RSCBot/commit/cd027b3ee1151db745e1855863a80f44fd16d3fa

2022-07-15 16:32 UTC, BenjaminHunt commented
another sloppy miss, but we're good now. Backwards compatibility patch: https://github.com/RSC-NA/bot-RSCBot/commit/7f7be591da0198b0bb24843f92a3ef7a446599a4

2022-07-15 17:34 UTC, BenjaminHunt commented
well at least match is cleaned up... https://github.com/RSC-NA/bot-RSCBot/commit/6ff084e1e4d653969339bd2b2d9530695a294d80

2022-07-15 17:37 UTC, BenjaminHunt commented
+ https://github.com/RSC-NA/bot-RSCBot/commit/6ff084e1e4d653969339bd2b2d9530695a294d80

2022-07-15 21:22 UTC, BenjaminHunt commented
+ time format bad https://github.com/RSC-NA/bot-RSCBot/commit/b9361bc44a78b209bfbf5b0c14d217c219dc767e

2022-07-15 21:40 UTC, BenjaminHunt commented
With all my heart, I believe this to be the last panic fix: https://github.com/RSC-NA/bot-RSCBot/commit/1ad7df4ceb90ae0516ca9a334f195da19699dec0