Bug quarantine fix
RSC-NA/bot-RSCBot pull request #8
Opened 2022-08-11 22:28 UTC by blister

I think the logical structure here is correct.

Need help with:

1. Remove role from all RSC servers.
2. Verifying any of this works in reality.
3. Figuring out what channel we're going to send "new messages" notifications to.

2022-08-11 22:30 UTC, BenjaminHunt commented
A bit picky, but I wouldn't say "fix," I'd say something like "resolution" or "compromise" or "workaround"

2022-08-11 22:50 UTC, BenjaminHunt commented on dmHelper/dmHelper.py
> +        self.bulk_role_manager_cog : BulkRoleManager = bot.get_cog("BulkRoleManager")
Best to remove circular dependency. Adding roles is pretty simple, and I'd prefer to go with the role removal approach.

2022-08-11 22:59 UTC, BenjaminHunt commented
So our solution should be:
```
- create role (you did, great!)
- create a command ?giveAllNeedsDMRole
- on listener for DMs:
  - remove needs DM role
  - send any saved messages
- on member join
  - if mutual guild --> we may want to patch this code on later
    - if other guild has needs dm role
      - if member has this role
        - add needs to dm bot role
```

2022-08-11 23:00 UTC, BenjaminHunt requested changes
A few things missing from our complete solution. I don't think we need 100% of it, but we should be adding the role on member join at minimum.

Might be good to localize the behavior to the guild just to get it working, then make a second PR for a full solution

2022-08-11 23:08 UTC, blister commented on dmHelper/dmHelper.py
> +                    log.debug(f"DM to recipient \"{recipient.name}\" failed due to Exception: {e}")
Yeah, I can do that. I didn't touch or turn off any of the existing code that was there.

2022-08-11 23:20 UTC, BenjaminHunt requested changes

2022-08-11 23:20 UTC, BenjaminHunt commented on dmHelper/dmHelper.py
> +    async def _message_listener(self, message: Discord.Message)
```suggestion
    async def _message_listener(self, message: discord.Message):
```
We should also use message type to only listen to DMs
![image](https://user-images.githubusercontent.com/16944592/184258218-b7face37-2e21-40a3-8011-68a167e6476d.png)

2022-08-12 16:09 UTC, blister commented
Love your changes. Looks very clean now. Nice job finding the listener `on_message_without_command`.

2022-08-13 05:44 UTC, BenjaminHunt approved these changes
Good Teamwork

2022-08-13 05:52 UTC, merged

2022-08-13 05:54 UTC, BenjaminHunt commented
## Message to other league admins

As you guys know, the bot was flagged as spam once again. This obviously blows, given the work we at the Dev Committee have put in to avoid this from happening on our new bot(s) but fortunately, the brilliant minds in the Dev Committee have devised what will likely be our best path forward.

### The Problem
The bot has now been "quarantined." We've discovered this _doesn't_ mean that it can't send DMs. It can't _initiate_ them. That's a big differentiation. So if players in the league DM the bot, then the bot can DM them back.

### Our Work-Around
The admins in the server must create a role, **Needs To DM Bot**, or some name of your choice. That's probably a good name so its consistent with RSC 3v3. This role will be assigned to all members within the server. You'll also need to create a new channel, (RSC 3v3 has **#please-dm-the-bot**. This channel's perms should be set so that nobody can send messages, and only Admins, Mods, Dev Committee, and Needs to DM Bot can view the channel.

This channel will have one concise message explaining the problem and that they need to DM the bot, so that it can DM them back. The bot will ghost ping players who need to DM the bot, so that they read that message and hopefully DM the bot, without clogging the channel for other players. This will be triggered whenever a player is assigned the role, either upon a failed DM, or a server join. When players DM the bot, it will remove this role. The admin commands to configure these channels after creation will be shared shortly.

We suggest this message:
> Hello! Unfortunately our RSC has been running into issues with the bots that are core to keeping this league running effectively. As a result, the bot can no longer send the first DM between any users.
> 
> We ask that you send the bot ANY message to enable DMs between you and the bot, and maximize your RSC experience!

### More Info
We will have some code in place to synchronize across all RSC servers, but we plan to improve it in a future iterations to cover edge cases better. Along with this, we intend to send previously failed messages when DMs are unlocked following this process.

If you have any questions, feel free to ping me. Just be aware that my responses may be a bit delayed as I am currently attending RLCS worlds.

We hope to get this solution out very soon.